### PR TITLE
Update new test questions

### PR DESCRIPTION
**Pull request by lorenanderson-itrellis**
- Also add a little more indentation formatting to the html.

When comparing, add ?w=1 to the url to ignore whitespace.

### CODE REVIEW

**Comment by matthewtabor-itrellis** [comment]
lgtm

**Comment by CarteriTrellis** [comment]
I don't know. I'm reluctant to eliminate the old tests entirely. I would add these into the mix, and maybe modify the ToDo list to require UI, or to require a .JSON file as a backing data source.

We know how the old tests work, and we know their strengths and weaknesses. I would like to keep them around while we figure out how these new tests perform.

**Comment by lorenanderson-itrellis** [comment]
@CarteriTrellis 
I thought we had a clear understanding of this work so I'm a little surprised by this. 

Part of the reason I originally proposed eliminating the old tests was lack of real programming logic. This is especially true for the to-do test. 

As far as unit tests go, the only piece of logic that can really be tested in the to-do list is the “if expiration is greater than right now, turn red”.

With that being said, I can re-do this to bring them back. But let's hash it out before I start work on it again.

**Comment by lorenanderson-itrellis** [comment]
@CarteriTrellis  I have updated this PR. Not deleting old questions. Added add'l requirements to todolist.

**Pull request merged**
